### ISSUE TITLE
Rename to hunt-entity

### ISSUE THREAD

**Issue by zoujiaqing** [huntlabs/entity#11]

**Comment by zoujiaqing** [comment]
When next hunt version release to change.

**Comment by ximion** [comment]
Does the name imply that the entity library will be coupled to hunt at some point? Or will it remain completely independent for the foreseeable future?

**Comment by zoujiaqing** [comment]
@ximion yes, hunt-entity is an independent project.
hunt rename to hunt-framework.
They keep the names consistent.

**Comment by ximion** [comment]
Nice! I welcome the change to a less generic name, makes adding the software to Linux distributions easier, and makes searching for the software simple and generally reduces confusion a lot.
