### ISSUE TITLE
ManyToMany does not appear to work

### ISSUE THREAD

**Issue by ximion** [huntlabs/entity#15]
Hi!
Given this artificial example of one blog page with multiple authors:
```d
@Table("users")
class User
{
    mixin MakeEntity;

    @PrimaryKey
    @AutoIncrement
    int id;

    string name;
    string email;

    @ManyToMany(FetchType.LAZY)
    Blog[] blogs;
}

@Table("blog")
class Blog
{
    mixin MakeEntity;

    @AutoIncrement @PrimaryKey
    int id;

    string title;
    string content;

    @ManyToMany(FetchType.LAZY)
    User[] users;
}
```
I would expect an additional table, like `users_blog_map` to be created and maintained to keep the ManyToMany relation in the database.
Instead, the relation simply gets ignored completely, with no changes being written to the database - so I am either using the feature wrong, or something is missing.

**Comment by zhangyuchun** [comment]
this feature isn't implemented.

**Comment by ximion** [comment]
Hmm, that's a shame, I have software based on HibernateD here that relies heavily on it and that can't be ported to hunt-entity without many-to-many relations.
Can you give any information on the priority of implementing this / some time estimate on when the feature might be done?
Is there something I can do to help having it added?

**Comment by zoujiaqing** [comment]
@ximion ManyToMany is worked.
