### ISSUE TITLE
Connect to SQLite3 database

### ISSUE THREAD

**Issue by boolangery** [huntlabs/entity#17]
Hi,
Do you have an example with sqlite database ?
I can't get it working.

I don't know how to fill EntityOption.
Thanks

**Comment by zhangyuchun** [comment]
after fixed a bug at https://github.com/huntlabs/hunt-database/commit/6ea0c409582bb1342a8de45511a4b0c9609c00a8
example:
auto option = new EntityOption;
option.database.database = "./testDB.db";
