### ISSUE TITLE
sqlite support seems incomplete?

### ISSUE THREAD

**Issue by aferust** [huntlabs/entity#25]
is it so?

**Comment by Heromyth** [comment]
Yes, the supports for SQLite are missing. A PR is welcomed.

**Comment by aferust** [comment]
Thank you. I have not enough background to do a PR in a short time for it yet. I was just looking for an ORM alternative for my [tutorial app](https://github.com/aferust/simplerestvibed) instead of hibernated (it looks like abandoned).
