### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by jairopaiva** [huntlabs/entity#27]
```
object.Error@rt\minfo.d(371): Cyclic dependency between module constructors/destructors of hunt.sql.visitor.SQLASTOutputVisitor and hunt.sql.ast.SQLObject
hunt.sql.visitor.SQLASTOutputVisitor* ->
hunt.sql.ast.statement.SQLInsertStatement ->
hunt.sql.ast.SQLObject* ->
hunt.sql.visitor.SQLASTVisitor ->
hunt.sql.ast.statement ->
hunt.sql.ast.statement.SQLUpdateStatement ->
hunt.sql.visitor.SQLASTOutputVisitor*
```

**Comment by Heromyth** [comment]
It's a long time before seeing this error again. Which version is used?

**Comment by jairopaiva** [comment]
It happens with last release (2.6.0) and also with the master branch.
Compiler: LDC (1.22.0)
Ide: VisualD (1.0.1-beta1)

**Comment by Heromyth** [comment]
We does not test it with Visual D. There is no problem with Visual Studio Code. 
So it not easy for us to reproduce this problem. But we will have a try lately.

**Comment by jairopaiva** [comment]
The problem occurs on execution, the compilation works normally, but when I run the program, I get this error. 
Tomorrow I will recreate the project and reference all dependencies locally, with their latest commits from the master branch.
Thanks for your time, HuntLabs' projects are spectacular!

**Comment by Heromyth** [comment]
You are welcome. We are trying our best to make it better and better.

The problem is because of `static this()` defined in these modules. It's not sure all of them have been removed. 

Because it occurs only on execution, we need a simple example to reproduce this. It can help us to fix it.

**Comment by jairopaiva** [comment]
Hello again, I redid the project referencing all dependencies locally (including between them), and I continue to receive the same error. I'm attaching the code I'm trying to execute
[project.zip](https://github.com/huntlabs/hunt-entity/files/4982618/project.zip)
...

**Comment by Heromyth** [comment]
> Hello again, I redid the project referencing all dependencies locally (including between them), and I continue to receive the same error. I'm attaching the code I'm trying to execute
> [project.zip](https://github.com/huntlabs/hunt-entity/files/4982618/project.zip)
> ...

There is no any problem. We have tested it on Windows and Linux with DUB.
However, there still are some improvements for this in commit https://github.com/huntlabs/hunt-sql/commit/d4aadb8b46ae0b161dc8c3be3392704d94a5322a. So, can you have a new test?

If the test still failed, would you attach your test project with Visual D?

**Comment by jairopaiva** [comment]
It worked, thank you all, you guys are awesome!

**Comment by Heromyth** [comment]
Then, what happened?
