### ISSUE TITLE
Quality of project

### ISSUE THREAD

**Issue by pasqui23** [huntlabs/entity#4]
I wanted to ask if the project is ready to be used,or if it still need more time to be developed

AlsoI can see that many lines in  the examples are commented,it is because they still do not work or what?

**Comment by zoujiaqing** [comment]
Wating one week time.

thanks your watch.

**Comment by zoujiaqing** [comment]
hello @pasqui23 , we publish release version [1.3.x](https://github.com/huntlabs/entity/releases) :)
The new version have stabled API.
